### ISSUE TITLE
Allow multiple Attic Floor Insulation and Attic Roof Insulation nodes

### ISSUE THREAD

**Issue by andrulis** [hpxmlwg/hpxml#28] opened 2015-03-30 23:48 UTC
When modeling an attic,  there may be multiple insulation sections for the floor or roof yet really be part of the same attic node.  Currently,  if there are multiple insulations sections, we need to artificially create multiple attics.  Instead,  I propose we can allow multiple attic floor insulation nodes and multiple attic roof insulation nodes.

**Comment by nmerket** [comment] 2015-04-07 19:36
Oh boy, this take something that's already kind of complicated and makes in complicateder. I see your reasoning and it makes sense. It would also be "non-breaking" in the strict sense that old files would validate against the updated schema. However, the extra layer of multiplicity it adds would be a real bear for receiving systems ([one of which](https://github.com/NREL/hescore-hpxml) I maintain now), so I'm hesitant to jump on this one without a wider discussion and consensus.

**Comment by GamalielL** [comment] 2015-04-07 19:44
Because this is backwards compatible, it wouldn't cause any problems for
us.  However, I'm of the general opinion that we shouldn't be adding
complications like this unless someone on the program implementation side
is pushing hard for them.

**Comment by kmwoley** [comment] 2015-04-07 21:04
Agreed.

**Comment by nmerket** [comment] 2015-10-19 14:49
I'm adding the 2.2 milestone because we should decide whether we're doing this or not doing this for that release.

**Comment by nmerket** [comment] 2015-11-30 20:09
Right now I have the following tally then:

for  | against
----|-----
@andrulis | @kmwoley 
 | @GamalielL 
 | @nmerket

## Reasons to add

 - Allows specification of real attics where there are areas of the attic floor and/or roof deck having different insulation levels.
 - Otherwise more than one attic must be defined to describe the physical properties of one.

## Reasons not to add

 - Forces those interpreting HPXML to have one more layer of multiplicity to deal with. 
 - The area is already on the Attic element. Would need to be moved down to the insulation elements, breaking backwards compatibility. 

## Conclusion

I'm leaning towards not doing this. @andrulis if you can persuade us otherwise, now is you're chance.

**Comment by andrulis** [comment] 2015-11-30 21:29
Right now to model an attic in a way that Savvy can interpret it for NYSERDA,  we need to artificially create multiple attics (one attic for every surface in the attic) and add an artificial area of 1 (since the Area node has a min exclusive of 0) when we are referring to a roof section.  There is no way to tell just how many attic spaces are actually in the home and the receiving systems needs to know to ignore if an attic Area = 1.

**Comment by jjaugenbraun** [comment] 2015-11-30 23:10
As I understand it, what we are doing at NYSERDA is actually the original intent of how to use the attic nodes in HPXML (with the exception of the Area = 1 workaround that is needed due to one of the savings reasonableness rules at NYSERDA). Since this process works for all of the modeling tools or they have a functioning workaround in place, I vote that we maintain the status quo.

**Comment by GamalielL** [comment] 2015-12-01 01:44
@andrulis can you explain why you end up needing to create Area=1 attics?
That's not something we have run into.

**Comment by jjaugenbraun** [comment] 2015-12-01 03:43
Hi Gamaliel,

Given the way NYSERDA attic insulation measures are defined, if the actual attic has improvements to both the AtticFloorInsulation and the AtticRoofInsulation systems, that would be conveyed as two separate attics in HPXML and two separate measures. Since each of those attics requires an area to be specified according to the NYSERDA data set and the HPXML schema does not permit an area of 0, we are using 1 so we can easily ignore these areas for reporting purposes and avoid double counting attic area (since both the AtticFloorInsulation and AtticRoofInsulation would be in the same actual attic in this case).

Thanks,
JJ

**Comment by GamalielL** [comment] 2015-12-01 14:20
JJ - That makes sense from an HPXML perspective, but I still don't
understand the real-life situation where you would be improving the
insulation in both surfaces in one attic.  It's my understanding that codes
in NY require you to remove attic floor insulation, if you are going to
insulate the roof deck.

**Comment by nmerket** [comment] 2015-12-01 15:33
Having to do a workaround hack like that isn't desirable. If making this change makes it so you don't have to do that, I'm all for it. I guess the question I have is whether allowing multiple `AtticFloorInsulation` and `AtticRoofInsulation` nodes would actually fix it since the `Area` is a subelement of the `Attic` and not the insulation nodes. 

![hpxml_attic](https://cloud.githubusercontent.com/assets/5325034/11505082/d8aa7096-9805-11e5-821b-7e6699a0e3a1.png)

If I could do this all over again I'd put the roof insulation on the `Roof` node. Maybe v3.

**Comment by jjaugenbraun** [comment] 2015-12-01 21:54
@GamalielL I'm not sure how often this happens in real life. @andrulis Do you have a sense for that?

@nmerket Since we have a workaround in place and this is a breaking change that not everyone may have had a chance to review, do you think we could table this change until v2.3?

**Comment by andrulis** [comment] 2015-12-02 17:52
The real life scenario is that only part of the attic floor is insulated.  Now, I have to create separate attic nodes for each variation in attic floor or roof insulation.  So instead of the attic indicating the concept of the attic 'space' and the floor and roof insulation indicating the concept of the 'surfaces' of that 'space',  we have to create a separate 'space' for each 'surface' and suddenly I have no idea if this building had one attic or multiple attics. 
  
I do like the idea of moving the roof insulation to the Roof node.  Perhaps we can do that in this release and deprecate the current attic roof insulation node with the idea to remove it in 3.0

**Comment by GamalielL** [comment] 2015-12-02 18:50
The problem is that Attics are halfway between a standalone insulation
surface component (like Wall) and a defined space (like Foundation) with an
unbounded number of insulation surface sub-nodes that each have their own
area.  I think that Rich would like them to be more like Foundations.  One
problem with that is that there can be insulated roof components that don't
belong to an Attic.  We already have AttachedToRoof/idref and
AtticKneeWall#/idref element in the Attic.  I think that the ideal scenario
would be to take that a step further and specify all insulation surfaces
outside of the Attic node, as follows:

   - Add a RoofInsulation insulation sub-node to the Roof node
   - Create a new AtticFloor node with Area element and
   AtticFloorInsulation sub-node
   - Add AttachedToFloor/idref and AttachedToWall/idref elments to the
   Attic node, so the Attic space can be associated with all bounding surfaces
   (roofs, gable walls, knee walls, and attic floors)

If we leave the existing insulation nodes inside Attic, then we can
maintain backwards compatibility for the time being.  They could be removed
in V3.

**Comment by nmerket** [comment] 2015-12-03 19:52
I will add an area to the insulation elements and post a pull request. Stay posted.

**Comment by GamalielL** [comment] 2015-12-03 19:56
Noel - Please review my proposal first.

**Comment by nmerket** [comment] 2015-12-03 20:21
@GamalielL, will do.

**Comment by nmerket** [comment] 2015-12-17 19:15
@GamalielL I think I like what you're proposing here, but having both in there for v2.2 is going to be a compatibility nightmare for receiving systems. Even though it's technically backwards compatible, it breaks the spirit of backwards compatibility. It will make anyone receiving HPXML have to parse both places and interpret it differently based on which elements are used (old or new). What if both are specified? 

A general re-working of attics is a great idea and it should be done. In v3.0.

**Comment by GamalielL** [comment] 2015-12-17 20:24
Let's leave this alone for now then.  I don't think it is adversely
affecting any programs at this point.

**Comment by andrulis** [comment] 2015-12-17 20:57
If you guys had seen the rather crappy workaround we had to do to make this work with the NYSERDA program, I think you'd be more agreeable to making the change now.  I really liked Gamaliel's proposal and I would argue that it is better to add it now and deprecate the existing functionality in v3.  That is a normal software versioning process.  Add a replacement feature in one release and deprecate the old feature in the next.  This gives software vendors time to phase in the change rather than having to scramble to adjust once v3 hits.

**Comment by nmerket** [comment] 2016-02-01 18:27
Still not quite sure what to do here, guys. Let's talk it through on the call Thursday.

**Comment by shorowit** [comment] 2019-02-07 23:46
This is addressed by the [proposed attic refactor](https://github.com/hpxmlwg/hpxml/issues/28) for v3.

**Closed** 2019-09-24 19:21 UTC
Labels: discussion needed, enhancement, schemas
